### ISSUE TITLE
2.3b2 - Window stacking order 

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#180]
Is it just me?

When I start TVRename 2.3b2 the splash screen appears to have focus and appears on top of any other open windows, however the main window always seems to appear behind anything else that's open.

I've checked with various applications open in the foreground and always have the same issue.

Andy B.

**Comment by JoeBiellik** [comment]
I can confirm I've also had this behavior for a while.

Strangely just commenting out ``SplashScreen.Show()`` in ``UI.cs`` fixes this but disables the splash screen. I can't see an obvious reason for why it causes the form to start in the background.

**Comment by MarkSummerville** [comment]
This looks like the issue https://stackoverflow.com/questions/392864/splash-screen-waiting-until-thread-finishes

Not quite sure how to fix it yet!

**Comment by MarkSummerville** [comment]
I think I've fixed it. Having said that, it has not been happening for me, so it would be good to get the new version tested

**Comment by Andy-ABTec** [comment]
Mark, If you can send me a zip of what I need to overwrite and I'd be happy to test - flitting about between TV Rename, Windows WSL/git, Doc web pages and GitHub is driving me round the bend. 8-)

**Comment by JoeBiellik** [comment]
@MarkSummerville I've tested the latest master code, and it does not seem to fix the issue for me or behave any different.

**Comment by MarkSummerville** [comment]
@JoeBiellik it's only in MarkSummerville/TVReanme/master - not merged back to main branch yet. Which did you test?

**Comment by MarkSummerville** [comment]
@Andy-ABTec - Sent a version for you yo try

**Comment by Andy-ABTec** [comment]
Got a copy from Marks dropbox 2.3b3 **Debug Build**

Making my workflow much easier now, I don't have to keep hunting for the window... (If only Microsoft would fix WSL and symbolic linking - then I'd be a really happy bunny!)

**Comment by MarkSummerville** [comment]
Link is here for anyone else who wants to try https://www.dropbox.com/s/6oiweb51rvqlywb/TVRename.exe?dl=0

**Comment by MarkSummerville** [comment]
OK  @Andy-ABTec sounds like it worked - will merge that in

**Comment by MarkSummerville** [comment]
Merged in, will be in the next beta - closing this issue
